// required: associates our `main.dart` with the code generated by Freezed
import 'package:freezed_annotation/freezed_annotation.dart';

part 'live_member_count.freezed.dart';
part 'live_member_count.g.dart';

@freezed
class LiveMemberCount with _$LiveMemberCount {
  const factory LiveMemberCount({
    required int liveId,
    required int memberCount,
  }) = _LiveMemberCount;

  factory LiveMemberCount.fromJson(Map<String, Object?> json) =>
      _$LiveMemberCountFromJson(json);
}
