name: app_main
description: A new Flutter module project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_core:
    path: ../app_core
  mobilehub_core:
    path: ../plugins/mobilehub/packages/mobilehub_core
  mobilehub_ui_core:
    path: ../plugins/mobilehub/packages/mobilehub_ui_core
  mobilehub_bloc:
    path: ../plugins/mobilehub/packages/mobilehub_bloc
  ui:
    path: ../ui
  design_system:
    path: ../design_system
  localization:
    path: ../localization
  reorderable:
    path: ../reorderable
  staggered_reorderable:
    path: ../staggered_reorderable

  intl: ^0.18.1
  http_parser: ^4.0.2
  freezed_annotation: ^2.4.1
  easy_device_media: ^1.0.0
  permission_handler: ^11.0.1

  cupertino_icons: ^1.0.6
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  injectable: ^2.3.2
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  adaptive_theme: ^3.4.1
  bot_toast: ^4.1.3
  top_snackbar_flutter: ^3.1.0
  bloc_concurrency: ^0.2.2
  rxdart: ^0.27.7
  imagewidget: ^1.1.0
  pretty_dio_logger: ^1.3.1
  focused_menu_custom: ^1.2.0
  dropdown_button2: ^2.3.9
  qr_code_scanner: ^1.0.1
  firebase_messaging: ^14.7.3
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.21.0
  equatable: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  qr_flutter: ^4.1.0
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  qr_code_dart_scan: ^0.7.3
  flutter_analog_clock: ^1.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  extended_nested_scroll_view: ^6.0.0
  pull_to_refresh: ^2.0.0
  camera: ^0.10.5+5
  google_mlkit_text_recognition: ^0.11.0
  google_ml_kit: ^0.16.3
  google_mlkit_commons: ^0.6.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.2
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.app_main
    iosBundleIdentifier: com.example.appMain
