name: app_main
description: A new Flutter module project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_core:
    path: ../app_core
  mobilehub_core:
    path: ../plugins/mobilehub/packages/mobilehub_core
  mobilehub_ui_core:
    path: ../plugins/mobilehub/packages/mobilehub_ui_core
  mobilehub_bloc:
    path: ../plugins/mobilehub/packages/mobilehub_bloc
  ui:
    path: ../ui
  design_system:
    path: ../design_system
  localization:
    path: ../localization
  reorderable:
    path: ../reorderable

  intl: ^0.18.1
  http_parser: ^4.0.2
  freezed_annotation: ^2.4.1
  easy_device_media: ^1.0.0
  permission_handler: ^11.0.1

  cupertino_icons: ^1.0.6
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  injectable: ^2.3.2
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  adaptive_theme: ^3.4.1
  bot_toast: ^4.1.3
  top_snackbar_flutter: ^3.1.0
  bloc_concurrency: ^0.2.2
  rxdart: ^0.27.7
  imagewidget: ^1.1.0
  pretty_dio_logger: ^1.3.1
  focused_menu_custom: ^1.2.0
  dropdown_button2: ^2.3.9
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.2
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.app_main
    iosBundleIdentifier: com.example.appMain
