include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: false
  errors:
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
