name: vdone_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_main:
    path: modules/app_main
  environments:
    path: modules/app_distribution/environments

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^8.0.1
  json_serializable: ^6.6.2
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
