name: design_system
description: A new Flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/icons/
    - assets/images/

  module:
    androidX: true
    androidPackage: com.example.design_system
    iosBundleIdentifier: com.example.designSystem
