name: design_system
description: A new Flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^2.3.0

dependency_overrides:
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:
  source_gen: ^1.2.7

flutter_gen:
  output: lib/generated/
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      style: snake-case
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/icons/dashboard/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400

  module:
    androidX: true
    androidPackage: com.example.design_system
    iosBundleIdentifier: com.example.designSystem
