// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'festival.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'festival.g.dart';

@freezed
class Festival with _$Festival {
  const factory Festival({
    int? id,
    int? userId,
    int? numberId,
    String? degree,
    String? music,
    List<String>? medias,
    String? createdAt,
    String? updatedAt,
    String? fullName,
    int? jaCode,
  }) = _Festival;

  factory Festival.fromJson(Map<String, Object?> json) =>
      _$FestivalFromJson(json);
}
