import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../domain/entities/gifter_info.dart';
import '../../../domain/entities/live_detail.dart';



// required: associates our `main.dart` with the code generated by Freezed
part 'gift_card_live.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'gift_card_live.g.dart';

@freezed
class GiftCardLive with _$GiftCardLive {
  const factory GiftCardLive(
      {LiveDetail? live,
      List<GiversInfo>? giversInfo,
      int? diamondCount}) = _GiftCardLive;

  factory GiftCardLive.fromJson(Map<String, Object?> json) =>
      _$GiftCardLiveFromJson(json);
}
