// required: associates our `main.dart` with the code generated by Freezed
// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../domain/entities/live_member_count.dart';

part 'member_count_data.freezed.dart';
part 'member_count_data.g.dart';

@freezed
class MemberCountData with _$MemberCountData {
  @JsonSerializable(explicitToJson: true)
  const factory MemberCountData({required List<LiveMemberCount> data}) =
      _MemberCountData;

  factory MemberCountData.fromJson(Map<String, Object?> json) =>
      _$MemberCountDataFromJson(json);
}
